# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    commit-message:
      prefix: "fix"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    reviewers:
      - "martinbacon"
    assignees:
      - "martinbacon"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    reviewers:
      - "martinbacon"
    assignees:
      - "martinbacon"